<?php

  /**
   * Theme definition
   */

  $theme['doctype'] = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN""."\n".""http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';
  $theme['highlight'] = '#e1e1e1';
  $theme['select'] = '';
  $theme['useframes'] = false;
  $theme['dispatcher'] = 'index.php';
  $theme['tabtype'] = 'dhtml';
  $theme['modern_menu_compat'] = true;
  $theme['compatible_menus'] = array('atk.menu.atkAccountingMenu');
  $theme['recordlist_orientation'] = 'left';
  $theme['recordlist_icons'] = true;
  $theme['relation_icons'] = true;
  $theme['basetheme'] = 'steelblue';

/*
  $theme['compatible_menus'] = array('atk.menu.atkDropdownMenu');
  $theme['menu_params'] = 'class='menulink'';
*/

?>