<?php
$tablemeta = array (
  'id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'id',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 5,
    'num' => 0,
  ),
  'title_id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'title_id',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 1,
  ),
  'userid' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'userid',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 2,
  ),
  'lastname' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'lastname',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 4,
    'num' => 3,
  ),
  'firstname' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'firstname',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 4,
  ),
  'initials' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'initials',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 5,
  ),
  'address' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'address',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 6,
  ),
  'zipcode' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'zipcode',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 7,
  ),
  'city' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'city',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 8,
  ),
  'state' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'state',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 9,
  ),
  'country' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'country',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 10,
  ),
  'phone' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'phone',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 11,
  ),
  'cellular' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'cellular',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 12,
  ),
  'fax' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'fax',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 13,
  ),
  'email' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'email',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 14,
  ),
  'function' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'function',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 15,
  ),
  'remark' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'remark',
    'type' => 252,
    'gentype' => 'text',
    'len' => 196605,
    'flags' => 0,
    'num' => 16,
  ),
  'role' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'role',
    'type' => 253,
    'gentype' => 'string',
    'len' => 45,
    'flags' => 4,
    'num' => 17,
  ),
  'created_by' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'created_by',
    'type' => 3,
    'gentype' => 'number',
    'len' => 11,
    'flags' => 0,
    'num' => 18,
  ),
  'created_on' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'created_on',
    'type' => 12,
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 19,
  ),
  'last_modified_by' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_by',
    'type' => 3,
    'gentype' => 'number',
    'len' => 11,
    'flags' => 0,
    'num' => 20,
  ),
  'last_modified_on' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_on',
    'type' => 12,
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 21,
  ),
  'birthdate' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'birthdate',
    'type' => 10,
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 22,
  ),
  'bankaccount' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 23,
  ),
  'socialsecuritynumber' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'socialsecuritynumber',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 24,
  ),
  'employer_id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'employer_id',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 25,
  ),
  'department' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'department',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 26,
  ),
  'supervisor' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'supervisor',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 27,
  ),
  'functionlevel' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'functionlevel',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 28,
  ),
  'status' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'status',
    'type' => 253,
    'gentype' => 'string',
    'len' => 27,
    'flags' => 0,
    'num' => 29,
  ),
  'lng' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'lng',
    'type' => 253,
    'gentype' => 'string',
    'len' => 6,
    'flags' => 0,
    'num' => 30,
  ),
  'password' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'password',
    'type' => 253,
    'gentype' => 'string',
    'len' => 120,
    'flags' => 0,
    'num' => 31,
  ),
  'theme' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'theme',
    'type' => 253,
    'gentype' => 'string',
    'len' => 42,
    'flags' => 0,
    'num' => 32,
  ),
  'company' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'company',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 33,
  ),
  'auth_server' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'auth_server',
    'type' => 253,
    'gentype' => 'string',
    'len' => 30,
    'flags' => 0,
    'num' => 34,
  ),
  'status_login' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'status_login',
    'type' => 254,
    'gentype' => 'string',
    'len' => 3,
    'flags' => 0,
    'num' => 35,
  ),
  'active_time' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'active_time',
    'type' => 3,
    'gentype' => 'number',
    'len' => 11,
    'flags' => 0,
    'num' => 36,
  ),
  'lastlogin' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'lastlogin',
    'type' => 12,
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 37,
  ),
)
?>